version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'sample_app'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db: