version: 2.1

orbs:
  docker: circleci/docker@0.5.20
  crystal: manastech/crystal@0.1.0

executors:
  crystal_mysql:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: crystallang/crystal:<< parameters.version >>
        environment:
          DATABASE_URL: mysql://root@localhost/sample_app
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: 'sample_app'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

commands:
  install_dockerize:
    parameters:
      version:
        type: string
        default: v0.6.1
    steps:
      - run:
          name: Install `curl` and `jq` for `docker/install-dockerize` command
          command: apt-get update && apt-get install -y curl jq
      - docker/install-dockerize
  wait_for_db:
    parameters:
      timeout:
        type: string
        default: 1m
      host:
        type: string
        default: tcp://localhost
      port:
        type: integer
        default: 3306
    steps:
      - install_dockerize
      - run:
          name: Wait for db using Dockerize
          command: dockerize -wait << parameters.host >>:<< parameters.port >> -timeout << parameters.timeout >>
  crystal_version:
    description: "Show Crystal and Shards version."
    steps:
      - run: |
          crystal --version
          shards --version

jobs:
  crystal_test:
    description: "Run tests with specified Crystal version"
    parameters:
      spec_options:
        type: string
        default: ""
      executor:
        description: The executor to use for this job.
        type: executor
        default: crystal/default
    executor: << parameters.executor >>
    steps:
      - crystal_version
      - checkout
      - crystal/cache_restore
      - crystal/shards_install
      - crystal/cache_save
      - crystal/test:
          spec_options: << parameters.spec_options >>

workflows:
  version: 2

  test:
    jobs:
      - crystal_test:
          name: Test on latest
          executor: crystal_mysql
          pre-steps:
            - wait_for_db

  # Run tests every night using crystal nightly
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - crystal_test:
          name: Test on nightly
          executor:
            name: crystal_mysql
            version: nightly
          pre-steps:
            - wait_for_db
