version: 2

jobs:
  test:
    docker:
      - image: crystallang/crystal:0.26.1
        environment:
          SHARDS_CACHE_PATH: ./shards-cache
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: 'sample_app'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    steps:
      - run: crystal --version

      - checkout

      - restore_cache:
          keys:
            - shards-cache-v1-{{ .Branch }}-{{ checksum "shard.lock" }}
            - shards-cache-v1-{{ .Branch }}
            - shards-cache-v1

      - run: shards

      - save_cache:
          key: shards-cache-v1-{{ .Branch }}-{{ checksum "shard.lock" }}
          paths:
            - ./shards-cache

      - run:
          name: Wait for MySQL
          command: sleep 5

      - run: crystal spec

workflows:
  version: 2
  # Run tests on every single commit
  ci:
    jobs:
      - test
